name: Readme
on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: 
    branches: ["main"]
jobs:
  readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: Europe/Berlin
          token: ${{ secrets.METRICS_TOKEN }}
          retries: 3
          retries_delay: 300
          config_display: large
          plugin_activity: true
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_introduction: true
          plugin_languages: true
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: rainbow
          plugin_languages_limit: 10
          plugin_lines: true
          plugin_lines_sections: base, repositories
          plugin_contributors: true
          plugin_contributors_contributions: true
